---
name: Compile Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool libtool-bin pkg-config libpurple-dev libjson-glib-dev libcurl4-openssl-dev libgtk-3-dev

      - name: Configure project
        run: ./autogen.sh && ./configure

      - name: Compile project
        run: make
